language: node_js
node_js:
  - stable

branches:
  only:
    - develop
cache:
  directories:
    - node_modules
env:
  global:
    JWT_SECRET_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0bmFtZSI6IkFwaHJvZGljZSIsImxhc3RuYW1lIjoiSXphYmF5byIsImVtYWlsIjoiaXphYmF5b2FwaHJvZGlzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFBiSHZEdmhkZmNESmRyeEdnMWxtYmVOUFdQN1hEcGtvWVhqN2JPejBtdm5QODRCT2t4UDZTIiwiaWF0IjoxNTcyMjk5MTM3LCJleHAiOjE1NzI4MTc1Mzd9.GwwwJP5aX_rLN_eNEkhucli1APJW80oQ-JgOqExjX70
    install:
  - npm install
  - npm install -g coveralls
script:
  - npm run test
after_success: 
  - npm run coveralls
sudo: false
