language: node_js
node_js:
  - stable

branches:
  only:
    - develop
cache:
  directories:
    - node_modules
env:
  global:
    JWT_SECRET_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0bmFtZSI6IkFwaHJvZGljZSIsImxhc3RuYW1lIjoiSXphYmF5byIsImVtYWlsIjoiaXphYmF5b2FwaHJvZGljZUBnbWFpbC5jb20iLCJpYXQiOjE1NzIyOTc5MTYsImV4cCI6MTU3MjgxNjMxNn0.Lbtw6i9RVql49AmmQvB6fzSmpDcriMYddva9CGphC0s
install:
  - npm install
  - npm install -g coveralls
script:
  - npm run test
after_success: 
  - npm run coveralls
sudo: false
