language: node_js
node_js:
  - stable

branches:
  only:
    - develop
cache:
  directories:
    - node_modules
env:
  global:
    JWT_SECRET_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0bmFtZSI6IkFwaHJvZGljZSIsImxhc3RuYW1lIjoiSXphYmF5byIsImVtYWlsIjoiaXphYmF5b2FwaHJvZGljZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRxRXpRTEhLeVQ0OG83Sks4a2dsaEguVFpEbjlaRU1idllGanppakljVmJKUkN3aGFMdlp2MiIsImlhdCI6MTU3MjI5NjQ1NywiZXhwIjoxNTcyODE0ODU3fQ.3bPqBqC0WtJQzAjyY2fEMiq-zbMuSXx_GdrD6822sWk
install:
  - npm install
  - npm install -g coveralls
script:
  - npm run test
after_success: 
  - npm run coveralls
sudo: false
